---
title: "Asymmetric tail associations in ecology"
slug: tails
category: research
order: 3
home: false
card-size: narrow
card-thumb-label: "tails"
card-summary: "Asymmetric tail associations in ecology"
card-detail: |
  Correlation between variables is more complex than commonly assumed, often including asymmetries which have widespread but seldom appreciated implications across the field of ecology — and which may also have caused the 2008 housing crisis.
thumbnail: "p3_half.jpg"
figure: "p3.jpg"
figure-caption: "Samples from two bivariate distributions with the same Pearson and Spearman correlations but with the association concentrated in the left vs. right tails."
figure-placement: "right"
figure-size: 0.66
---

We discovered in the course of our other work that a simple statistical idea has 
far-reaching implications in ecology. When two variables are positively related
in ecology, that association is usually described very simply with a single number,
typically a correlation coefficient (Pearson, Spearman). But in fact the non-marginal information content 
of a joint distribution is a much higher dimensional object. A useful second dimension
turns out to be the degree of asymmetry of the association in the tails. These ideas
turn out to be far reaching, influencing phenomena as diverse as the 2008 financial
crisis, extinction risk, spatial and community synchrony, Taylor's law, and 
ecological stability. We have studied the nature, causes, and ecological consequences
of asymmetries of tail associations in ecological variables 
over a period of several years, with an 
ongoing interest.

J.A. Walter, M.C.N. Castorani, T.W. Bell, L.W. Sheppard, K.C. Cavanaugh, D.C. Reuman. 2022. Tail-dependent spatial synchrony arises from nonlinear driver-response relationships. Ecology Letters 25, 1189-1201. doi: 10.1111/ele.13991. 

S. Ghosh, K.L. Cottingham, D.C. Reuman. 2021. Species relationships in the extremes and their influence on community stability. Philosophical Transactions of the Royal Society B 376, 20200343. doi: 10.1098/rstb.2020.0343.

S. Ghosh, L.W. Sheppard, P.C. Reid, D.C. Reuman. 2020. A new approach to interspecific synchrony in population ecology using tail association. Ecology and Evolution 10, 12764-12776. doi: 10.1002/ece3.6732.

S. Ghosh, L.W. Sheppard, D.C. Reuman. 2020. Tail associations in ecological variables and their impact on extinction risk. Ecosphere 11, e03132. doi: 10.1002/ecs2.3132.

S. Ghosh, L.W. Sheppard, M.T. Holder, T.E. Loecke, P.C. Reid, J.D. Bever, D.C. Reuman. 2020. Copulas and their potential for ecology. Advances in Ecological Research 62, 409-468. doi: 10.1016/bs.aecr.2020.01.003. 

People: [Shyamolina Ghosh](../../../people.qmd#shyamolina-ghosh), [Lawrence Sheppard](../../../people.qmd#lawrence-sheppard), [Jon Walter](../../../people.qmd#jonathan-walter), Dan Reuman
